// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgX_AKpCAU6GwO-kionawDgGlMg7TIY5Q',
    appId: '1:929688219642:android:0f39bf2290689b62e73e43',
    messagingSenderId: '929688219642',
    projectId: 'flutly-store',
    storageBucket: 'flutly-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrXQ0t0SCcC7ZbHfP1n93iYAB2jAsJZVA',
    appId: '1:929688219642:ios:7f1cab63c8fdc350e73e43',
    messagingSenderId: '929688219642',
    projectId: 'flutly-store',
    storageBucket: 'flutly-store.firebasestorage.app',
    androidClientId: '929688219642-8sb280deadieq32ttcloprmafn2ai5rk.apps.googleusercontent.com',
    iosClientId: '929688219642-uohc1lnflcucaq8r013kt6a5n9eeidij.apps.googleusercontent.com',
    iosBundleId: 'dev.bernes.flutlystore',
  );

}